#include <vtk/vtkCamera.h>
#include <vtk/vtkColorTransferFunction.h>
#include <vtk/vtkOpenGLGPUVolumeRayCastMapper.h>
#include <vtk/vtkPiecewiseFunction.h>
#include <vtk/vtkOpenGLRenderWindow.h>
#include <vtk/vtkOpenGLRenderer.h>
#include <vtk/vtkImageReader.h>
#include <vtk/vtkImageData.h>
#include <vtk/vtkJPEGWriter.h>
#include <vtk/vtkPointData.h>
#include <vtk/vtkVolume.h>
#include <vtk/vtkMultiVolume.h>
#include <vtk/vtkVolumeProperty.h>
#include <vtk/vtkUnsignedCharArray.h>